// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OSTech.EFCore.Context;

#nullable disable

namespace OSTech.EFCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260712212938_AddCustomerCategoryEquipment")]
    partial class AddCustomerCategoryEquipment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("OSTech.Domain.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "Serviços relacionados à infraestrutura de TI.",
                            Name = "Infraestrutura"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "Serviços de redes e conectividade.",
                            Name = "Redes"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "Manutenção e substituição de componentes.",
                            Name = "Hardware"
                        },
                        new
                        {
                            CategoryId = 4,
                            Description = "Firewall, antivírus e segurança da informação.",
                            Name = "Segurança"
                        },
                        new
                        {
                            CategoryId = 5,
                            Description = "Rotinas de backup e recuperação.",
                            Name = "Backup"
                        });
                });

            modelBuilder.Entity("OSTech.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Document = "12.345.678/0001-90",
                            Email = "contato@techsolutions.com",
                            Name = "Tech Solutions LTDA",
                            Phone = "11-2222-1111"
                        },
                        new
                        {
                            CustomerId = 2,
                            Document = "23.456.789/0001-12",
                            Email = "suporte@escolaalpha.com",
                            Name = "Escola Alpha",
                            Phone = "11-3333-2222"
                        },
                        new
                        {
                            CustomerId = 3,
                            Document = "34.567.890/0001-45",
                            Email = "contato@bompreco.com",
                            Name = "Mercado Bom Preço",
                            Phone = "11-4444-3333"
                        },
                        new
                        {
                            CustomerId = 4,
                            Document = "45.678.901/0001-67",
                            Email = "ti@clinicavida.com",
                            Name = "Clínica Vida",
                            Phone = "11-5555-4444"
                        },
                        new
                        {
                            CustomerId = 5,
                            Document = "56.789.012/0001-89",
                            Email = "suporte@lojadigital.com",
                            Name = "Loja Digital",
                            Phone = "11-6666-5555"
                        });
                });

            modelBuilder.Entity("OSTech.Domain.Entities.Equipment", b =>
                {
                    b.Property<int>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EquipmentId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("EquipmentId");

                    b.ToTable("Equipments");

                    b.HasData(
                        new
                        {
                            EquipmentId = 1,
                            Brand = "Dell",
                            Model = "PowerEdge R650",
                            Name = "Servidor Dell",
                            SerialNumber = "SRV001"
                        },
                        new
                        {
                            EquipmentId = 2,
                            Brand = "Cisco",
                            Model = "Catalyst 2960",
                            Name = "Switch Cisco",
                            SerialNumber = "SW002"
                        },
                        new
                        {
                            EquipmentId = 3,
                            Brand = "Lenovo",
                            Model = "ThinkPad E14",
                            Name = "Notebook Lenovo",
                            SerialNumber = "NT003"
                        },
                        new
                        {
                            EquipmentId = 4,
                            Brand = "Fortinet",
                            Model = "FortiGate 60F",
                            Name = "Firewall Fortinet",
                            SerialNumber = "FW004"
                        },
                        new
                        {
                            EquipmentId = 5,
                            Brand = "HP",
                            Model = "ProLiant DL380",
                            Name = "Servidor Backup",
                            SerialNumber = "BK005"
                        });
                });

            modelBuilder.Entity("OSTech.Domain.Entities.Technician", b =>
                {
                    b.Property<int>("TechnicianId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TechnicianId"));

                    b.Property<bool>("Availability")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateOnly>("HiringDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("TechnicianId");

                    b.ToTable("Technicians");

                    b.HasData(
                        new
                        {
                            TechnicianId = 1,
                            Availability = true,
                            Contact = "11-2222-2222",
                            HiringDate = new DateOnly(2023, 2, 11),
                            Name = "Marcelo Silva",
                            Specialty = "Engenharia de Software"
                        },
                        new
                        {
                            TechnicianId = 2,
                            Availability = true,
                            Contact = "11-9999-1111",
                            HiringDate = new DateOnly(2022, 6, 5),
                            Name = "Ana Costa",
                            Specialty = "Redes de Computadores"
                        },
                        new
                        {
                            TechnicianId = 3,
                            Availability = false,
                            Contact = "11-8888-3333",
                            HiringDate = new DateOnly(2021, 9, 20),
                            Name = "Bruno Almeida",
                            Specialty = "Segurança da Informação"
                        },
                        new
                        {
                            TechnicianId = 4,
                            Availability = true,
                            Contact = "11-7777-4444",
                            HiringDate = new DateOnly(2024, 1, 10),
                            Name = "Juliana Ferreira",
                            Specialty = "Desenvolvimento Web"
                        },
                        new
                        {
                            TechnicianId = 5,
                            Availability = true,
                            Contact = "11-6666-5555",
                            HiringDate = new DateOnly(2020, 3, 15),
                            Name = "Ricardo Mendes",
                            Specialty = "DevOps"
                        });
                });

            modelBuilder.Entity("OSTech.Domain.Entities.WorkOrder", b =>
                {
                    b.Property<int>("WorkOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WorkOrderId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Deadline")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("OpeningDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TechnicianId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("WorkOrderId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("TechnicianId");

                    b.ToTable("WorkOrders");

                    b.HasData(
                        new
                        {
                            WorkOrderId = 1,
                            Amount = 3500.00m,
                            CategoryId = 1,
                            CustomerId = 1,
                            Deadline = new DateOnly(2026, 7, 10),
                            Description = "Instalar e configurar servidor Linux para ambiente corporativo.",
                            EquipmentId = 1,
                            OpeningDate = new DateOnly(2026, 7, 1),
                            Status = 0,
                            TechnicianId = 1,
                            Title = "Instalação de Servidor"
                        },
                        new
                        {
                            WorkOrderId = 2,
                            Amount = 980.00m,
                            CategoryId = 2,
                            CustomerId = 2,
                            Deadline = new DateOnly(2026, 7, 8),
                            Description = "Resolver problemas de conectividade entre os laboratórios.",
                            EquipmentId = 2,
                            OpeningDate = new DateOnly(2026, 7, 2),
                            Status = 1,
                            TechnicianId = 2,
                            Title = "Manutenção da Rede"
                        },
                        new
                        {
                            WorkOrderId = 3,
                            Amount = 1450.00m,
                            CategoryId = 3,
                            CustomerId = 3,
                            Deadline = new DateOnly(2026, 6, 30),
                            Description = "Substituir HD por SSD em cinco computadores.",
                            EquipmentId = 3,
                            OpeningDate = new DateOnly(2026, 6, 25),
                            Status = 2,
                            TechnicianId = 1,
                            Title = "Troca de SSD"
                        },
                        new
                        {
                            WorkOrderId = 4,
                            Amount = 2200.00m,
                            CategoryId = 4,
                            CustomerId = 4,
                            Deadline = new DateOnly(2026, 7, 15),
                            Description = "Criar regras de segurança para acesso remoto.",
                            EquipmentId = 4,
                            OpeningDate = new DateOnly(2026, 7, 3),
                            Status = 0,
                            TechnicianId = 4,
                            Title = "Configuração de Firewall"
                        },
                        new
                        {
                            WorkOrderId = 5,
                            Amount = 1800.00m,
                            CategoryId = 5,
                            CustomerId = 5,
                            Deadline = new DateOnly(2026, 7, 5),
                            Description = "Implantar rotina automática de backup diário.",
                            EquipmentId = 5,
                            OpeningDate = new DateOnly(2026, 6, 28),
                            Status = 3,
                            TechnicianId = 3,
                            Title = "Backup Corporativo"
                        });
                });

            modelBuilder.Entity("OSTech.Domain.Entities.WorkOrder", b =>
                {
                    b.HasOne("OSTech.Domain.Entities.Category", "Category")
                        .WithMany("WorkOrders")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OSTech.Domain.Entities.Customer", "Customer")
                        .WithMany("WorkOrders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OSTech.Domain.Entities.Equipment", "Equipment")
                        .WithMany("WorkOrders")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OSTech.Domain.Entities.Technician", "Technician")
                        .WithMany("WorkOrders")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Customer");

                    b.Navigation("Equipment");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("OSTech.Domain.Entities.Category", b =>
                {
                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("OSTech.Domain.Entities.Customer", b =>
                {
                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("OSTech.Domain.Entities.Equipment", b =>
                {
                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("OSTech.Domain.Entities.Technician", b =>
                {
                    b.Navigation("WorkOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
