// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OSTech.EFCore.Context;

#nullable disable

namespace OSTech.EFCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260704183152_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("OSTech.Domain.Entities.Technician", b =>
                {
                    b.Property<int>("TechnicianId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TechnicianId"));

                    b.Property<bool>("Availability")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateOnly>("HiringDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("TechnicianId");

                    b.ToTable("Technicians");

                    b.HasData(
                        new
                        {
                            TechnicianId = 1,
                            Availability = true,
                            Contact = "11-2222-2222",
                            HiringDate = new DateOnly(2023, 2, 11),
                            Name = "Marcelo Silva",
                            Specialty = "Engenharia de Software"
                        },
                        new
                        {
                            TechnicianId = 2,
                            Availability = true,
                            Contact = "11-9999-1111",
                            HiringDate = new DateOnly(2022, 6, 5),
                            Name = "Ana Costa",
                            Specialty = "Redes de Computadores"
                        },
                        new
                        {
                            TechnicianId = 3,
                            Availability = false,
                            Contact = "11-8888-3333",
                            HiringDate = new DateOnly(2021, 9, 20),
                            Name = "Bruno Almeida",
                            Specialty = "Segurança da Informação"
                        },
                        new
                        {
                            TechnicianId = 4,
                            Availability = true,
                            Contact = "11-7777-4444",
                            HiringDate = new DateOnly(2024, 1, 10),
                            Name = "Juliana Ferreira",
                            Specialty = "Desenvolvimento Web"
                        },
                        new
                        {
                            TechnicianId = 5,
                            Availability = true,
                            Contact = "11-6666-5555",
                            HiringDate = new DateOnly(2020, 3, 15),
                            Name = "Ricardo Mendes",
                            Specialty = "DevOps"
                        });
                });

            modelBuilder.Entity("OSTech.Domain.Entities.WorkOrder", b =>
                {
                    b.Property<int>("WorkOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WorkOrderId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateOnly>("Deadline")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<DateOnly>("OpeningDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TechnicianId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("WorkOrderId");

                    b.HasIndex("TechnicianId");

                    b.ToTable("WorkOrders");

                    b.HasData(
                        new
                        {
                            WorkOrderId = 1,
                            Amount = 3500.00m,
                            Client = "Tech Solutions LTDA",
                            Deadline = new DateOnly(2026, 7, 10),
                            Description = "Instalar e configurar servidor Linux para ambiente corporativo.",
                            OpeningDate = new DateOnly(2026, 7, 1),
                            Status = 0,
                            TechnicianId = 1,
                            Title = "Instalação de Servidor"
                        },
                        new
                        {
                            WorkOrderId = 2,
                            Amount = 980.00m,
                            Client = "Escola Alpha",
                            Deadline = new DateOnly(2026, 7, 8),
                            Description = "Resolver problemas de conectividade entre os laboratórios.",
                            OpeningDate = new DateOnly(2026, 7, 2),
                            Status = 1,
                            TechnicianId = 2,
                            Title = "Manutenção da Rede"
                        },
                        new
                        {
                            WorkOrderId = 3,
                            Amount = 1450.00m,
                            Client = "Mercado Bom Preço",
                            Deadline = new DateOnly(2026, 6, 30),
                            Description = "Substituir HD por SSD em cinco computadores.",
                            OpeningDate = new DateOnly(2026, 6, 25),
                            Status = 2,
                            TechnicianId = 1,
                            Title = "Troca de SSD"
                        },
                        new
                        {
                            WorkOrderId = 4,
                            Amount = 2200.00m,
                            Client = "Clínica Vida",
                            Deadline = new DateOnly(2026, 7, 15),
                            Description = "Criar regras de segurança para acesso remoto.",
                            OpeningDate = new DateOnly(2026, 7, 3),
                            Status = 0,
                            TechnicianId = 4,
                            Title = "Configuração de Firewall"
                        },
                        new
                        {
                            WorkOrderId = 5,
                            Amount = 1800.00m,
                            Client = "Loja Digital",
                            Deadline = new DateOnly(2026, 7, 5),
                            Description = "Implantar rotina automática de backup diário.",
                            OpeningDate = new DateOnly(2026, 6, 28),
                            Status = 3,
                            TechnicianId = 3,
                            Title = "Backup Corporativo"
                        });
                });

            modelBuilder.Entity("OSTech.Domain.Entities.WorkOrder", b =>
                {
                    b.HasOne("OSTech.Domain.Entities.Technician", "Technician")
                        .WithMany("WorkOrders")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("OSTech.Domain.Entities.Technician", b =>
                {
                    b.Navigation("WorkOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
